show jest test results nicely in Github

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -40,3 +40,10 @@ jobs:
         run: yarn
       - name: Run All Tests
         run: yarn test:ci
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Jest Tests            # Name of the check run which will be created
+          path: jest-*.xml            # Path to test results
+          reporter: jest-junit        # Format of test results
